[package]
name = "partly-proxy-runner"
description = "Minimal binary wrapper around partly-proxy-lib."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"

[lib]
path = "src/lib.rs"

[[bin]]
name = "partly-proxy-runner"
path = "src/main.rs"

[dependencies]
partly-proxy-lib = { path = "../partly-proxy-lib" }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
partly-proxy-echo = { path = "../partly-proxy-echo" }
